FROM python:3.10.0

WORKDIR /usr/app

RUN apt-get update \
    && apt-get install -y python3-dev
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel

COPY ./setup/ ./setup/
RUN pip3 install --no-cache-dir -r ./setup/packages_app

#COPY ./entrypoint.sh ./entrypoint.sh
#RUN chmod +x /usr/app/entrypoint.sh

COPY . .

EXPOSE 80 81
EXPOSE 8000

#ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
