# Generated by Django 4.0.2 on 2022-02-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('segmento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('data', models.DateField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
            options={
                'db_table': 'dates',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('plano', models.CharField(choices=[('bronze', 'brass'), ('prata', 'silver'), ('ouro', 'gold'), ('platina', 'platinum')], max_length=10)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=100)),
                ('integer', models.IntegerField()),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='RawPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('data_pagamento', models.DateField()),
                ('valor', models.FloatField()),
                ('qtde_meses_pagos', models.IntegerField()),
                ('plano', models.ForeignKey(help_text='plan related to the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.plan')),
            ],
            options={
                'db_table': 'raw_payments',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('valor', models.FloatField()),
                ('qtde_meses_pagos', models.IntegerField()),
                ('data', models.ForeignKey(help_text='payment date', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.date')),
                ('plano', models.ForeignKey(help_text='plan related to the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='financial.plan')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
