# Generated by Django 4.0.2 on 2022-02-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=None, help_text='customer that made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='financial.customer'),
        ),
    ]
