# Generated by Django 4.0.2 on 2022-02-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_payment_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='plano',
            new_name='plan',
        ),
    ]
